trainer:
  max_epochs: 100
  logger:
    class_path: lightning.pytorch.loggers.wandb.WandbLogger
    init_args:
      resume: allow
      project: "eomt"
      name: "iscar_bp_panoptic_eomt_large_640_dinov3"
model:
  class_path: training.mask_classification_panoptic.MaskClassificationPanoptic
  init_args:
    ckpt_path: "checkpoints/eomt_large_640.bin"
    num_classes: 2
    load_ckpt_class_head: False
    use_area_weighting: True
    attn_mask_annealing_enabled: True
    attn_mask_annealing_start_steps: [0, 29564, 44346, 59128]
    attn_mask_annealing_end_steps: [3000, 44346, 59128, 73910]
    lr: 2e-4
    llrd_l2_enabled: False
    warmup_steps: [2000, 3000]
    delta_weights: True
    network:
      class_path: models.eomt.EoMT
      init_args:
        enable_occlusion: True
        num_q: 200
        encoder:
          class_path: models.vit.ViT
          init_args:
            backbone_name: facebook/dinov3-vitl16-pretrain-lvd1689m

data:
  class_path: datasets.iscar_bp.ReplicatorDataModule
  init_args:
    path: "/home/kaelin/BinPicking/SDG/IS/Outputs/batch_5"
    stuff_classes: [0]
    num_classes: 2
    batch_size: 4